name: Java CI/CD with Gradle

on:
  push:
    branches: [ main, development2, restructure ]
  pull_request:
    branches: [ main, development2, restructure ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ci_test_password_2025
          MYSQL_DATABASE: adauang_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      
      - name: Wait for MySQL to be ready
        run: |
          echo " Waiting for MySQL to start..."
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -P 3306 -u root -p"ci_test_password_2025" --silent; then
              echo " MySQL is ready!"
              break
            fi
            echo "Attempt $i: MySQL not ready yet, waiting 5 seconds..."
            sleep 5
          done
      
      - name: Setup Database Schema
        run: |
          echo " Creating database tables..."
          mysql -h 127.0.0.1 -P 3306 -u root -p"ci_test_password_2025" adauang_db << 'EOF'
          
          -- Table users
          CREATE TABLE IF NOT EXISTS users (
            id INT PRIMARY KEY AUTO_INCREMENT,
            username VARCHAR(255) NOT NULL,
            email VARCHAR(255) NOT NULL,
            password VARCHAR(255) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          );

          -- Table kontrak
          CREATE TABLE IF NOT EXISTS kontrak (
            id INT PRIMARY KEY AUTO_INCREMENT,
            user_id INT,
            branch VARCHAR(255),
            title VARCHAR(255),
            content TEXT,
            amount DECIMAL(15,2),
            status VARCHAR(50),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id) REFERENCES users(id)
          );

          -- Table cicilan  
          CREATE TABLE IF NOT EXISTS cicilan (
            id INT PRIMARY KEY AUTO_INCREMENT,
            kontrak_id INT,
            user_id INT,
            amount DECIMAL(15,2),
            paid_amount DECIMAL(15,2) DEFAULT 0,
            due_date DATE,
            payment_date DATE NULL,
            status VARCHAR(50) DEFAULT 'pending',
            description TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (kontrak_id) REFERENCES kontrak(id),
            FOREIGN KEY (user_id) REFERENCES users(id)
          );

          -- Table contracts (jika ada yang pakai nama ini)
          CREATE TABLE IF NOT EXISTS contracts (
            id INT PRIMARY KEY AUTO_INCREMENT,
            user_id INT,
            title VARCHAR(255),
            content TEXT,
            amount DECIMAL(15,2),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id) REFERENCES users(id)
          );

          EOF
          
          echo " Verifying tables created successfully:"
          mysql -h 127.0.0.1 -P 3306 -u root -p"ci_test_password_2025" -e "USE adauang_db; SHOW TABLES;"
          
          echo " Showing table structures:"
          mysql -h 127.0.0.1 -P 3306 -u root -p"ci_test_password_2025" -e "USE adauang_db; DESCRIBE users; DESCRIBE kontrak; DESCRIBE cicilan;"
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      - name: Build with Gradle
        env:
          CI_DB_PASSWORD: ci_test_password_2025
        run: ./gradlew build --no-daemon --info
      
      - name: Run Tests
        env:
          CI_DB_PASSWORD: ci_test_password_2025
        run: ./gradlew test --no-daemon --info
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: build/reports/tests/